/** Generated by scripts/activate.ts. */
export const themeConfig = {
	defaultMode: 'system',
	enabledModes: ['light', 'dark', 'system'] as const,
	cookieName: 'golden-svelte-platform_theme'
} as const;

export type ThemeMode = (typeof themeConfig.enabledModes)[number];
