/** Generated by scripts/activate.ts. Edit project.manifest.yaml and reactivate instead. */
export const projectConfig = {
	name: 'golden-svelte-platform',
	displayName: 'Golden Svelte Platform',
	description: 'A governed Svelte 5 application platform.',
	version: '0.1.0',
	locales: ['pt-BR', 'en', 'fr', 'es'] as const,
	sourceLocale: 'pt-BR',
	themeDefault: 'system',
	serviceName: 'golden-svelte-platform'
} as const;

export type SupportedLocale = (typeof projectConfig.locales)[number];
